import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import Auth from "~/components/auth";
import Button from "~/components/ui/button";
import PostView from "~/components/post-view";
import Loading from '~/components/ui/loading';

const Home = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return (
    <div className='w-screen h-screen flex items-center justify-center'>
      <Loading />
    </div>
  );

  if (!data) return <div>Something went wrong!</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <div
          className="flex h-full w-full flex-col items-center
          border-x border-slate-400 md:max-w-4xl"
        >
          <div className="w-full border-b border-slate-400">
            <Auth />
            {user.isSignedIn && (
              <div className="mb-4 flex items-center justify-between gap-6 px-6 py-4">
                <div className="grow rounded-md border-2 border-slate-400 focus-within:border-slate-200">
                  <input
                    type="text"
                    placeholder="Type some emojis!"
                    className="h-full w-full border-none bg-transparent px-4 py-2 outline-none"
                  />
                </div>
                <Button>Add</Button>
              </div>
            )}
          </div>
          <div className="flex w-full flex-col">
            {[...data]?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
