import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import { api } from "~/utils/api";

import Auth from "~/components/auth";
import Feed from "~/components/feed";
import CreatePost from "~/components/create-post";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  //Start fetching asap
  api.posts.getAll.useQuery();

  //Return empty div if user isn't loaded
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center">
        <div
          className="flex h-full w-full flex-col items-center
          border-x border-slate-400 md:max-w-4xl"
        >
          <div className="w-full border-b border-slate-400">
            <Auth />
            {isSignedIn && <CreatePost />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
