import Head from "next/head";
import { useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import { api } from "~/utils/api";

import Auth from "~/components/auth";
import Button from "~/components/ui/button";
import Feed from "~/components/feed";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();

  //Start fetching asap
  api.posts.getAll.useQuery();

  //Return empty div if user isn't loaded
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <div
          className="flex h-full w-full flex-col items-center
          border-x border-slate-400 md:max-w-4xl"
        >
          <div className="w-full border-b border-slate-400">
            <Auth />
            {isSignedIn && (
              <div className="mb-4 flex items-center justify-between gap-6 px-6 py-4">
                <div className="grow rounded-md border-2 border-slate-400 focus-within:border-slate-200">
                  <input
                    type="text"
                    placeholder="Type some emojis!"
                    className="h-full w-full border-none bg-transparent px-4 py-2 outline-none"
                  />
                </div>
                <Button>Add</Button>
              </div>
            )}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
